// <auto-generated />
namespace Practica1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3ramigracion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3ramigracion));
        
        string IMigrationMetadata.Id
        {
            get { return "201701261616141_3ra migracion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
